### ISSUE TITLE
cannot display nerdtree with tmux plugin resurrect-strategy-vim

### ISSUE THREAD

**Issue by L-Jovi** [dhruvasagar/vim-prosession#49]
Hi, thanks for your smart lib :)

I use tmux plugin which called resurrect-strategy-vim and vim-obsession coexist that help me recover session, but nerdtree window always gone.

Then I try to use vim-prosession rather exec `:Obsession` command inside vim, but sometimes nerdtree show in a mess.

How shoud I fix it.

My env:
osx: 10.13.4
bash
tmux: 2.3
vim: 8.0

Thanks for your time.

**Comment by dhruvasagar** [comment]
Hi, you're welcome!

Most of these issues aren't really prosession specific or even obsession specific, it's the way these special nerdtree buffers (similarly for other special buffers like netrw etc) are configured to be handled by vim. My suggestion is to get away from the habbit of always having the buffer open, just open it when you need it and keep it closed otherwise, that will help you get better usage of the available real-estate within vim and also leave out issues like these.
