### ISSUE TITLE
Problems with filenames and creating new session.

### ISSUE THREAD

**Issue by AndreaHasani** [dhruvasagar/vim-prosession#58]
Prosession commands makes a clean session (is that how its supposed to work). If there are open buffers it closes them. Also the filename is kind of weird with the absolute directory from where the session is being created as part of the filename.

**Comment by dhruvasagar** [comment]
With vim-prosession and vim-obsession, the session is created as soon as you launch vim from your project directory, and is regularly updated as you make changes such as open / close buffers etc. If you close and reopen vim (perhaps using `:qa`) in the same directory prosession will load the saved session for the current directory and load that and it would re-open all your buffers as they were when you closed vim.

When you use the command `Prosession path` it does the following : 
* Persist the current session and stop further tracking
* Delete all loaded buffers from vim
* Find the session file for the `path` directory, if one exists already it loads it, otherwise it just starts empty starting a new session for that directory. Any subsequent changes you make from then onwards will be persisted within the `path` directory's session.

**Comment by AndreaHasani** [comment]
Sorry about that I misunderstood what this plugin was supposed to do.
